# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rb_user', '0002_auto_20180414_0656'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpinionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oname', models.CharField(max_length=20)),
                ('oyijian', models.CharField(max_length=200)),
                ('ophone', models.CharField(default='', max_length=11)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rb_user.UesrInfo')),
            ],
        ),
    ]
